name: Build and Create Artifact

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master  

jobs:
  build:
    runs-on: windows-latest  

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  

    - name: Restore dependencies and build
      working-directory: ./DevOpsProject
      run: |
        dotnet restore ./DevOpsProject.sln
        dotnet build ./DevOpsProject.sln --configuration Release

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyAppArtifacts
        path: |
          ./bin/Debug/net6.0-windows/*.exe  # Adjust this path to your built .exe file
          /DevOpsProject/bin/Debug/net6.0-windows/*.dll  # Adjust this path to include necessary DLLs